version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: latest
      - node/with-cache:
          steps:
            - run: ls
            - run: 
              name: Refresh data from NYT
              command: cd ./data-constructor/ && ls && npm install && npm run refresh && npm start
            - run: 
              name: Build App
              command: cd ./app/ && ls && npm install && npm build
            - run:
                name: Deploy
                command: curl -X POST -d {} ${hook}
workflows:
    build-and-test:
      jobs:
        - build