version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build:
    executor:
      name: node/default
    resource_class: xlarge
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: yarn install
          app-dir: ~/project/app
      - node/install-packages:
          override-ci-command: yarn install
          app-dir: ~/project/data-constructor
      - run: 
          name: Refresh data from NYT
          command: cd ./data-constructor/ && ls && npm run refresh && npm start
      - run: 
          name: Build App
          command: cd ./app/ && ls && CI=false npm run build
      - run:
          name: Deploy
          command: npm install netlify-cli -g && netlify deploy --prod --dir ./app/build --message "site deployed from circle ci"  --site covid-19-stat-map
workflows:
    build-and-test:
      jobs:
        - build