version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          install-yarn: true
          app-dir: ~/project/app
      - node/install-packages:
          install-yarn: true
          app-dir: ~/project/data-constructor
      - run: 
          name: Refresh data from NYT
          command: cd ./data-constructor/ && ls && npm run refresh && npm start
      - run: 
          name: Build App
          command: cd ./app/ && ls && npm run build
      - run:
          name: Deploy
          command: curl -X POST -d {} ${hook}
workflows:
    build-and-test:
      jobs:
        - build