version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: latest
      - node/with-cache:
          steps:
            - run: ls
            - run: WORKDIR ./data-constructor/
            - run: ls
            - run: npm install
            - run: npm run refresh
            - run: npm start
            - run: WORKDIR ../app/
            - run: ls
            - run: npm install
            - run: npm build
workflows:
    build-and-test:
      jobs:
        - build